# Generated by Django 5.2.5 on 2025-08-13 04:08

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='well',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('wellname', models.CharField(max_length=255)),
                ('componyname', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
