# Generated by Django 5.2.5 on 2025-08-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIOC_Production_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoretype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NIOC_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('NIOC_Production_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osduapp.nioc_production_type')),
                ('shore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osduapp.shoretype')),
            ],
        ),
    ]
