# Generated by Django 5.2.5 on 2025-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='XCOORDINATE',
        ),
        migrations.AddField(
            model_name='field',
            name='X_COORDINATE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='Y_COORDINATE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=10, null=True),
        ),
    ]
