# Generated by Django 5.2.5 on 2025-09-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0002_remove_field_xcoordinate_field_x_coordinate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POOL_STATUS',
            fields=[
                ('POOL_STATUS_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('POOL_STATUS_NAME', models.CharField(max_length=200)),
                ('ROW_CREATED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('ROW_CREATED_DATE', models.DateTimeField(blank=True, null=True)),
                ('ROW_CHANGED_DATE', models.DateTimeField(blank=True, null=True)),
                ('ROW_CHANEGED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='POOL_TYPE',
            fields=[
                ('POOL_TYPE_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('POOL_TYPE_NAME', models.CharField(max_length=200)),
                ('SHORTNAME', models.CharField()),
                ('LONGNAME', models.CharField()),
                ('ROW_CREATED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('ROW_CREATED_DATE', models.DateTimeField(blank=True, null=True)),
                ('ROW_CHANGED_DATE', models.DateTimeField(blank=True, null=True)),
                ('ROW_CHANEGED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='POOL',
            fields=[
                ('POOL_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('POOL_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('POOL_CODE', models.CharField(blank=True, max_length=200, null=True)),
                ('POOL_NAME_ABBERATION', models.CharField(blank=True, max_length=200, null=True)),
                ('ROW_CREATED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('ROW_CREATED_DATE', models.DateTimeField(blank=True, null=True)),
                ('ROW_CHANGED_DATE', models.DateTimeField(blank=True, null=True)),
                ('ROW_CHANEGED_BY', models.CharField(blank=True, max_length=200, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('POOL_STATUS_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osduapp.pool_status')),
                ('POOL_TYPE_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osduapp.pool_type')),
            ],
        ),
    ]
