# Generated by Django 5.2.5 on 2025-08-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0002_nioc_production_type_shoretype_nioc_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='testidd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shoretype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
