# Generated by Django 5.2.5 on 2025-09-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0003_pool_status_pool_type_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool_type',
            name='IS_ACTIVE',
        ),
        migrations.RemoveField(
            model_name='pool_type',
            name='LONGNAME',
        ),
        migrations.RemoveField(
            model_name='pool_type',
            name='ROW_CHANEGED_BY',
        ),
        migrations.RemoveField(
            model_name='pool_type',
            name='ROW_CHANGED_DATE',
        ),
        migrations.RemoveField(
            model_name='pool_type',
            name='ROW_CREATED_BY',
        ),
        migrations.RemoveField(
            model_name='pool_type',
            name='ROW_CREATED_DATE',
        ),
        migrations.RemoveField(
            model_name='pool_type',
            name='SHORTNAME',
        ),
    ]
