# Generated by Django 5.2.5 on 2025-08-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0003_testidd_alter_shoretype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testidd',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
