# Generated by Django 5.2.5 on 2025-09-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0004_remove_pool_type_is_active_remove_pool_type_longname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool_type',
            name='IS_ACTIVE',
            field=models.BooleanField(default=True),
        ),
    ]
