# Generated by Django 5.2.5 on 2025-08-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0004_alter_testidd_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='testiddd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osduapp.testidd')),
            ],
        ),
    ]
