# Generated by Django 5.2.5 on 2025-09-06 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osduapp', '0005_pool_type_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('FORMATION_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FORMATION_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='r_well_status_type',
            name='R_SOURCE_ID',
        ),
        migrations.CreateModel(
            name='ZONE',
            fields=[
                ('ZONE_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(blank=True, max_length=200, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('POOL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osduapp.pool')),
            ],
        ),
    ]
